"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pk-resizer.py']
DATA_FILES = ['configuration.cfg']
OPTIONS = {'argv_emulation': True, 'resources': ['configuration.cfg']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
